vroom/Controllers/BikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vroom.AddDbContext;
using vroom.Models;
using vroom.Models.ViewModel;
using vroom.Helpers;
using System.IO;
using Microsoft.AspNetCore.Hosting.Internal;
using cloudscribe.Pagination.Models;

namespace vroom.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
    public class BikeController : Controller
    {
        private readonly VroomDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;


        [BindProperty]
        public BikeViewModel BikeVM { get; set; }

        public BikeController(VroomDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;

            BikeVM = new BikeViewModel()
            {
                Makes = _db.Makes.ToList(),
                Models = _db.Models.ToList(),
                Bike = new Models.Bike()
            };
        }

        
        [AllowAnonymous]
        public IActionResult Index(string searchString, string sortOrder, int pageNumber=1, int pageSize=25)
        {

            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortOrder) ? "price_desc" : "";
            int ExcludeRecords = (pageSize * pageNumber) - pageSize;
            var Bikes = from b in _db.Bikes.Include(m => m.Make).Include(m => m.Model)
                        select b;

            var BikeCount = Bikes.Count();

            if (!String.IsNullOrEmpty(searchString))
            {
                Bikes = Bikes.Where(b => b.Make.Name.Contains(searchString));
                BikeCount = Bikes.Count();

            }

            //Sorting Logic
            switch (sortOrder)
            {
                case "price_desc":
                    Bikes = Bikes.OrderByDescending(b => b.Price);
                    break;
                default:
                    Bikes = Bikes.OrderBy(b => b.Price);
                    break;
            }

            Bikes=Bikes.Skip(ExcludeRecords)
                .Take(pageSize);

            var result = new PagedResult<Bike>
            {
                Data = Bikes.AsNoTracking().ToList(),
                TotalItems = BikeCount,
                PageNumber = pageNumber,
                PageSize = pageSize
            };

            return View(result);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            BikeVM.Bike = _db.Bikes.SingleOrDefault(b=>b.Id==id);

            //Filter the models associated to the selected make
            BikeVM.Models = _db.Models.Where(m => m.MakeFK == BikeVM.Bike.MakeID);

            if (BikeVM.Bike==null)
            {
                return NotFound();
            }

            return View(BikeVM);
        }

        [HttpPost, ActionName("Edit")]

        public IActionResult EditPost()
        {

            if (!ModelState.IsValid)
            {
                BikeVM.Makes = _db.Makes.ToList();
                BikeVM.Models = _db.Models.ToList();
                return View(BikeVM);
            }

            _db.Bikes.Update(BikeVM.Bike);

            UploadImageIfAvailable();

            _db.SaveChanges();

           
            /////////////////


            return RedirectToAction(nameof(Index));
        }

        //get method
        public IActionResult Create()
        {

            return View(BikeVM);
        }

        //post method
        [HttpPost, ActionName("Create")]
        
        public IActionResult CreatePost()
        {

            if (!ModelState.IsValid)
            {
                BikeVM.Makes = _db.Makes.ToList();
                BikeVM.Models = _db.Models.ToList();
                return View(BikeVM);
            }

            _db.Bikes.Add(BikeVM.Bike);

            UploadImageIfAvailable();
            
                _db.SaveChanges();



            

            /////////////////


            return RedirectToAction(nameof(Index));
        }

        private void UploadImageIfAvailable()
        {
            //Save bike logic
            /////////////////
            ///

            //get bike id we have saved in db

            var BikeID = BikeVM.Bike.Id;

            //get wwwwrootpath to save the file on server
            string wwrootPath = _hostingEnvironment.WebRootPath;

            //get the uploaded files
            var files = HttpContext.Request.Form.Files;

            //get the references if DBSet for the bike we just have saved in database
            var SavedBike = _db.Bikes.Find(BikeID);

            //Upload the files on server and save the image path of user have uploaded any file
            if (files.Count != 0)
            {
                var ImagePath = @"images\bike\";
                var Extension = Path.GetExtension(files[0].FileName);
                var RelativeImagePath = ImagePath + BikeID + Extension;
                var AbsImagePath = Path.Combine(wwrootPath, RelativeImagePath);

                //Upload the file on server
                using (var fileStream = new FileStream(AbsImagePath, FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                //set the image path on database
                SavedBike.ImagePath = RelativeImagePath;
            }
        }

        //public IActionResult Edit(int id)
        //{

        //    ModelVM.Model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);

        //    if (ModelVM.Model == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(ModelVM);
        //}

        //[HttpPost, ActionName("Edit")]
        //public IActionResult EditPost(int id)
        //{

        //    if (!ModelState.IsValid)
        //    {
        //        return View(ModelVM);
        //    }

        //    _db.Update(ModelVM.Model);
        //    _db.SaveChanges();
        //    return RedirectToAction(nameof(Index));
        //}

        [HttpPost]
        public IActionResult Delete(int id)
        {

            Bike bike = _db.Bikes.Find(id);

            if (bike == null)
            {
                return NotFound();
            }

            _db.Bikes.Remove(bike);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        [AllowAnonymous]
        [HttpGet("api/models/{MakeID}")]
        public IEnumerable<Model> Models(int MakeID)
        {
            return _db.Models.ToList()
                .Where(m => m.MakeFK == MakeID);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult View(int id)
        {
            BikeVM.Bike = _db.Bikes.SingleOrDefault(b => b.Id == id);

            

            if (BikeVM.Bike == null)
            {
                return NotFound();
            }

            return View(BikeVM);
        }
    }
}

vroom/Controllers/MakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using vroom.AddDbContext;
using vroom.Models;
using vroom.Helpers;
namespace vroom.Controllers
{
    [Authorize(Roles = Roles.Admin + "," + Roles.Executive)]
    public class MakeController : Controller
    {
        //[Route("Make")]
        //[Route("Make/Bikes")]
        //public IActionResult Bikes()
        //{
        //   Make make = new Make {Id=1, Name = "Harley Davidson" };

        //    return View(make);

        //    //ContentResult cr = new ContentResult { Content = "Hello World" };

        //    //return cr;

        //    //return Content("Hey this is the string from helper method");
        //    //return Redirect("/home");
        //    //return RedirectToAction("About", "Home");

        //    //return new EmptyResult();//no retorna nada al view

        //}

        //[Route("make/bikes/{year:int:length(4)}/{month:int:range(1,12)}")]
        //public IActionResult ByYearMoth(int year, int month)
        //{
        //    return Content(year+";"+month);
        //}

        private readonly VroomDbContext _db;

        public MakeController(VroomDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Makes.ToList());
        }
        //Get method
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Make make)
        {

            if (ModelState.IsValid)
            {
                _db.Add(make);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(make);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {

            var make = _db.Makes.Find(id);
            if (make==null)
            {
                return NotFound();
            }
            _db.Makes.Remove(make);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {

            var make = _db.Makes.Find(id);
            if (make == null)
            {
                return NotFound();
            }
            
            return View(make);
        }
        [HttpPost]
        public IActionResult Edit(Make make)
        {

            if (ModelState.IsValid)
            {
                _db.Update(make);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(make);
        }

    }
}

vroom/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vroom.AddDbContext;
using vroom.Models;
using vroom.Models.ViewModel;
using vroom.Helpers;
using vroom.Controllers.Resources;
using AutoMapper;

namespace vroom.Controllers
{
    [Authorize(Roles = Roles.Admin+","+Roles.Executive)]
    public class ModelController : Controller
    {
        private readonly VroomDbContext _db;
        private readonly IMapper _mapper;

        [BindProperty]
        public ModelViewModel ModelVM { get; set; }

        public ModelController(VroomDbContext db, IMapper mapper)
        {
            _db = db;
            _mapper = mapper;
            ModelVM = new ModelViewModel()
            {
                Makes = _db.Makes.ToList(),
                Model = new Models.Model()
            };
        }

        public IActionResult Index()
        {
            var model = _db.Models.Include(m=>m.Make);
            return View(model);
        }

        public IActionResult Create()
        {
            
            return View(ModelVM);
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost()
        {

            if (!ModelState.IsValid)
            {
                return View(ModelVM);
            }

            _db.Models.Add(ModelVM.Model);
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(int id)
        {

            ModelVM.Model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);

            if (ModelVM.Model==null)
            {
                return NotFound();
            }

            return View(ModelVM);
        }

        [HttpPost, ActionName("Edit")]
        public IActionResult EditPost()
        {

            if (!ModelState.IsValid)
            {
                return View(ModelVM);
            }

            _db.Update(ModelVM.Model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            
            Model model = _db.Models.Find(id);
           List<Bike> model1 = _db.Bikes.Where(m=>m.ModelID==id).ToList();

            if (model==null)
            {
                return NotFound();
            }
            _db.Bikes.RemoveRange(model1);
            _db.Models.Remove(model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        [AllowAnonymous]
        [HttpGet("api/models")]
        public IEnumerable<ModelResources> Models()
        {
            //return _db.Models.ToList();
            var models = _db.Models.ToList();

            //create mapper configuration
            //var config = new MapperConfiguration(mc => mc.CreateMap<Model, ModelResources>());

            //map the objects
            //var mapper = new Mapper(config);
            return _mapper.Map<List<Model>, List<ModelResources>>(models);

            //var modelResources = models
            //    .Select(m => new ModelResources
            //    {
            //        Id = m.Id,
            //        Name = m.Name

            //    }).ToList();

            //return modelResources;
                
        }



    }
}

vroom/Views/Shared/_Layout.cshtml
@using vroom.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - vroom</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/all.css" rel="stylesheet">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/all.css" rel="stylesheet">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    </environment>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" asp-controller="Bike" asp-action="Index">Vroom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Bike" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                {


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Masters
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Make" asp-action="Index">Makes</a>
                            <a class="dropdown-item" asp-controller="Model" asp-action="Index">Models</a>
                            <a class="dropdown-item" asp-controller="Bike" asp-action="Index">Bikes</a>

                            @if (User.IsInRole(Roles.Admin))
                            {
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Add User</a>
                            }

                        </div>
                </li>
                }
            </ul>
           <partial name="_LoginPartial"/>
        </div>
    </nav>



    @*<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">vroom</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="navbar-link dropdown-toggle" href="#" id="navbarDropdown" role="button">Masters</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Make" asp-action="Index">Makes</a>
                            <a class="dropdown-item" href="#">Models</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>*@



    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - vroom</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>*@

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

vroom/Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber=(int)Model.PageNumber
          cs-paging-totalitems=(int)Model.TotalItems
          cs-paging-pagesize=Model.PageSize
          cs-pagenumber-param="pagenumber"
          asp-route-searchString="@ViewBag.CurrentFilter" 
          asp-route-sortOrder="@ViewBag.CurrentSortOrder"
          asp-controller=@ViewData["Controller"]
          asp-action=@ViewData["Action"]
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">

</cs-pager>

vroom/Views/Shared/_TablaButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td class="text-right">
    <div class="btn-group" rold="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)"><i class="far fa-edit"></i></a>
        @*<a type="button" class="btn btn-primary" href="@Url.Action("Delete/"+item.Id)" value="Delete"></a>*@
        <form method="post" action="Delete">
            <button onclick="if (!confirm('Are you sure you want to delete this item')){return false}" type="submit" class="btn btn-danger rounded-0" asp-action="Delete" asp-route-id="@Model"><i class="far fa-trash-alt"></i></button>
        </form>
    </div>
</td>